spring.datasource.url = jdbc:postgresql://localhost:5432/alexis
spring.datasource.username = postgres
spring.datasource.password = postgres
spring.datasource.driver-class-name = org.postgresql.Driver

# Configurarea JPA
spring.jpa.hibernate.ddl-auto = update
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect

# Configurare de logare pentru JPA (op?ional)
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
